FROM node:24-alpine AS build

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml ./

RUN pnpm install

COPY . .

RUN pnpm build

RUN cp -r public .next/standalone/

FROM node:24-alpine AS prod

WORKDIR /app

COPY --from=build /app/.next/standalone ./

EXPOSE 3000